---
- name: Install Packages
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      
- include_tasks: install_dotfiles.yml
  with_items:
    - { src: 'nvim/init.vim', dest: '.config/nvim', file: 'init.vim' }
    - { src: 'nvim/coc-settings.json', dest: '.config/nvim', file: 'coc-settings.json' }
