#!/usr/bin/env bash
# sops + age. Installs the pinned upstream sops binary (Debian's package lags)
# plus age from apt. Prepares $HOME/.config/sops/age/ but does NOT generate a
# key — admin laptops bring their own; the per-server deploy user gets its
# key generated by modules/bare-git-repo.
set -euo pipefail

readonly SOPS_VERSION="3.12.2"
readonly SOPS_SHA256="14e2e1ba3bef31e74b70cf0b674f6443c80f6c5f3df15d05ffc57c34851b4998"
readonly SOPS_URL="https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64"
readonly SOPS_DST=/usr/local/bin/sops

apt_ensure age

# Distro sops lags. Remove it so the upstream binary on PATH wins.
if apt_installed sops; then
  if [[ "${DRY_RUN:-0}" == 1 ]]; then
    info "would: sudo apt-get purge -y sops"
  else
    sudo apt-get purge -y sops
    ok "purged distro sops package"
  fi
fi

need_install=1
if [[ -x "$SOPS_DST" ]]; then
  current="$("$SOPS_DST" --version --disable-version-check 2>/dev/null | head -1 || true)"
  if [[ "$current" == *"$SOPS_VERSION"* ]]; then
    ok "sops already at $SOPS_VERSION ($SOPS_DST)"
    need_install=0
  else
    info "sops present but version differs: $current — will update"
  fi
fi

if (( need_install )); then
  if [[ "${DRY_RUN:-0}" == 1 ]]; then
    info "would: download $SOPS_URL (sha256 ${SOPS_SHA256:0:12}…) -> $SOPS_DST"
  else
    tmp="$(mktemp)"
    trap 'rm -f -- "$tmp"' EXIT
    curl -fsSL --retry 3 -o "$tmp" -- "$SOPS_URL"
    actual_sha="$(sha256sum -- "$tmp" | awk '{print $1}')"
    if [[ "$actual_sha" != "$SOPS_SHA256" ]]; then
      die "sops sha256 mismatch: expected $SOPS_SHA256, got $actual_sha"
    fi
    sudo install -m 0755 -o root -g root -- "$tmp" "$SOPS_DST" || die "install $SOPS_DST"
    ok "installed sops $SOPS_VERSION ($SOPS_DST)"
  fi
fi

# Per-user age key directory. Don't generate the key — admins bring their own.
age_dir="$HOME/.config/sops/age"
if [[ "${DRY_RUN:-0}" == 1 ]]; then
  info "would: mkdir -p $age_dir (mode 0700)"
  exit 0
fi

mkdir -p -- "$age_dir"
chmod 700 -- "$age_dir"

if [[ -s "$age_dir/keys.txt" ]]; then
  ok "age key present at $age_dir/keys.txt"
else
  warn "no age key at $age_dir/keys.txt"
  warn "  place your private admin age key there, or generate one with:"
  warn "    age-keygen -o $age_dir/keys.txt"
  warn "  back up the file — losing it locks you out of every sops-encrypted secret."
fi
