#!/bin/bash

default_username="ms"
packages="sudo python3 ansible git"
github_url="https://github.com/stromdahl/configs.git"

if [[ $EUID -ne 0 ]]; then
    echo "this script must be run as root" 
    exit 1
fi

echo "-- Install packages --"
for package in $packages; do
    echo "$package"
    apt -y install $package > /dev/null 2>&1
done
echo -- OK --

echo "-- Create User --"
read -p "username: ($default_username): " username
username=${username:-$default_username}
while true; do
    read -p "password: : " password
    echo ""
    read -p "repeat password: : " password_repeat
    echo ""
    if [ "$password" == "$password_repeat"]: then
        break
    else
        echo "Passwords do not match. Please try again."
    fi
done
echo -- OK --

echo "-- Running Ansible Playbook --"
ansible-playbook "local.yml"
echo -- OK --
