---
  - hosts: localhost
    tasks:
      - name: "Check user credentials"
        assert:
          that:
            - username is defined
            - password is defined

  - hosts: localhost
    become: true
    pre_tasks:
      - name: install updates
        apt:
          upgrade: dist
          update_cache: yes

  - hosts: localhost
    become: true
    tasks:

      - name: Collect info 
        block:
          - name: Collect public ssh key from github
            ansible.builtin.set_fact:
              sshkeys: "{{ lookup('ansible.builtin.url', 'https://github.com/stromdahl.keys') }}"
          - name: Collect available local users
            ansible.builtin.getent:
              database: passwd

      - name: Add user
        block:

          - name: "create user '{{ username }}'"
            tags: always
            user:
              name: "{{ username }}"
              password: "{{ password | password_hash('sha512') }}"
              groups: root
            when: username not in getent_passwd.keys()

          - name: "add ssh key for '{{ username }}'"
            tags: always
            authorized_key:
              user: "{{ username }}"
              key: "{{ sshkeys }}"

          - name: "add sudoers file for {{ username }}"
            tags: always
            copy:
              content: "ms ALL=(ALL) NOPASSWD: ALL"
              dest: "/etc/sudoers.d/{{ username }}"
              owner: root
              group: root
              mode: 0440
