---
- name: Install Packages
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      i3

- include_tasks: install_dotfiles.yml
  with_items:
    - { src: 'i3/config', dest: '.config/i3', file: 'config' }
    - { src: 'i3status/config', dest: '.config/i3status', file: 'config' }

- name: Ensure /etc/X11/xorg.conf.d exists
  become: yes
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: Copy xorg custom settings
  become: yes
  copy:
    src: 90-custom-xkb.conf
    dest: /etc/X11/xorg.conf.d/90-custom-xkb.conf

