# Modules to install on 'krypton' (laptop). One per line.
# See modules/<name>/install.sh for what each does.

base
ssh
bash
git
gtk
userdirs
xkb

# Editor
nvim

# Languages
node

# Wayland/sway desktop
sway
waybar
foot
kanshi
mako
swaync

# Utilities
yazi
syncthing
battery-guardian
