---
- name: Install useful tools
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - bc
      - git
      - gpg
      - htop
      - jq
      - man-db
      - molly-guard
      - mosquitto-clients
      - ncdu
      - net-tools
      - ntp
      - pv
      - ripgrep
      - unattended-upgrades
      - vim
