---
- name: Setup Unattended Upgrade
  become: yes
  copy:
    content: "APT::Periodic::Update-Package-Lists \"1\";\nAPT::Periodic::Unattended-Upgrade \"1\";"
    dest: /etc/apt/apt.conf.d/02auto-upgrades
