---
  - name: Create "{{ homeassistant_process_group }}"  group
    group:
      name: "{{ homeassistant_process_group }}"
      state: present

  - name: Create "{{ homeassistant_process_owner }}"  user
    user:
      name: "{{ homeassistant_process_owner }}"
      group: "{{ homeassistant_process_group }}"
      create_home: no
      shell: /bin/false
      state: present

  - name: Allow homeassistant user to run Docker commands without sudo
    user:
      name: "{{ homeassistant_process_owner }}"
      groups: docker
      append: yes 
  
  - name: Create homeassistant folder
    file:
      path: "/opt/homeassistant"
      state: directory
      mode: '0755'
      owner: "{{ homeassistant_process_owner }}"
      group: "{{ homeassistant_process_group }}"

  - name: Start homeassistant
    become: "{{ homeassistant_process_owner }}"
    community.docker.docker_compose:
      project_name: homeassistant
      definition:
        version: '3'
        services:
          homeassistant:
            container_name: homeassistant
            image: "homeassistant/home-assistant:{{ homeassistant_version }}"
            volumes:
              - /opt/homeassistant:/config
              - /etc/localtime:/etc/localtime:ro
            restart: unless-stopped
            ports:
              - 8123
    register: output

  - name: Show results
    ansible.builtin.debug:
      var: output

  - name: Verify that the db and web services are running
    ansible.builtin.assert:
      that:
        - "output.services.homeassistant.homeassistant_homeassistant_1.state.running"
