---
- name: i3wm | install packages
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - i3
      - xorg
      - xinit

- name: Ensute i3 start on login
  ansible.builtin.blockinfile:
    path: ~/.profile
    block: | 
      if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
        exec startx
      fi
