---
- name: 'Create directory ({{item.src}})'
  file: 
    path: '{{ ansible_user_dir }}/{{item.dest}}'
    state: directory

- name: 'Stat dotfile ({{item.src}})'
  stat:
    path: '{{ansible_user_dir}}/{{item.dest}}/{{item.file}}'
  register: dotfile_stat

- name: 'Delete original dotfile ({{item.src}})'
  when: dotfile_stat.stat.isreg is defined and dotfile_stat.stat.isreg == True
  file:
    path: '{{ansible_user_dir}}/{{item.dest}}/{{item.file}}'
    state: absent

- name: 'Symlink dotfile ({{item.src}})'
  file:
    src: '{{dotfiles_dir}}/.dotfiles/configs/{{item.src}}'
    dest: '{{ansible_user_dir}}/{{item.dest}}/{{item.file}}'
    state: link
