---
- name: Checkout dotfiles
  git:
    force: false
    update: false
    accept_hostkey: yes
    repo: git@github.com:Stromdahl/configs.git
    dest: '{{ dotfiles_dir }}/.dotfiles'

- include_tasks: install_dotfiles.yml
  with_items:
    - { src: 'bash/bashrc', dest: '', file: '.bashrc' }
    - { src: 'miscelanius/gitconfig', dest: '', file: '.gitconfig' }

- include_tasks: i3wm/main.yml
  when: i3wm is defined and i3wm == true
