---
- name: Checkout dotfiles
  git:
    force: false
      # TODO: fix update true when changes is made localy 
    update: false
    accept_hostkey: yes
    repo: git@github.com:Stromdahl/configs.git
    dest: '{{ dotfiles_dir }}/.dotfiles'

- include_tasks: install_dotfiles.yml
  with_items:
    - { src: 'bash/bashrc', dest: '', file: '.bashrc' }
    - { src: 'miscelanius/gitconfig', dest: '', file: '.gitconfig' }
    - { src: 'miscelanius/xsessionrc', dest: '', file: '.xsessionrc' }
    - { src: 'miscelanius/user-dirs.dirs', dest: '.config', file: 'user-dirs.dirs' }
    - { src: 'xfce4-terminal/terminalrc', dest: '.config/xfce4/terminal', file: 'terminalrc' }
    - { src: 'xfce4-terminal/gruvbox-dark-hard.theme', dest: '.local/share/xfce4/terminal/colorschemes', file: 'gruvbox-dark-hard.theme' }

- include_tasks: i3wm/main.yml
  when: i3wm is defined and i3wm == true

- include_tasks: nvim/main.yml
  when: nvim is defined and nvim == true


