---
- include_tasks: install-dotfiles.yml
  with_items:
    - { src: 'bash/bashrc', dest: '', file: '.bashrc' }
    - { src: 'i3', dest: '.config/i3', file: 'config' }
    - { src: 'miscelanius/gitconfig', dest: '', file: '.gitconfig' }
    - { src: 'miscelanius/user-dirs.dirs', dest: '.config', file: 'user-dirs.dirs' }
      # - { src: 'xfce4-terminal/terminalrc', dest: '.config/xfce4/terminal', file: 'terminalrc' }
      # - { src: 'xfce4-terminal', dest: '.local/share/xfce4/terminal', file: 'colorschemes' }
    #  - { src: 'miscelanius/xsessionrc', dest: '', file: '.xsessionrc' }
