---
- name: laptop test
  debug:
    msg: laptop test

- name: Ensure HandleLidSwitch
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf 
    regexp: 'HandleLidSwitch='
    line: HandleLidSwitch=suspend

- name: Ensure HandleLidSwitchExternalPower
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf 
    regexp: 'HandleLidSwitchExternalPower='
    line: HHandleLidSwitchExternalPower=ignore

- name: Ensure HandleLidSwitchDocked
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf 
    regexp: 'HandleLidSwitchDocked='
    line: HHandleLidSwitchDocked=ignore
