---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install SwayWM and dependencies
  apt:
    name:
      - sway
      - wayland-protocols
      - libwayland-dev
      - libwlroots-dev
      - swaybg
      - swayidle
      - swaylock
      - xwayland
    state: present

- name: Install LightDM
  apt:
    name: lightdm
    state: present

- name: Enable LightDM to start on boot
  systemd:
    name: lightdm
    enabled: yes
    state: started

- name: Create Sway configuration directory
  file:
    path: /home/{{ ansible_user_id }}/.config/sway
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

## - name: Copy default Sway configuration
##   copy:
##     src: /etc/sway/config
##     dest: /home/{{ ansible_user_id }}/.config/sway/config
##     remote_src: yes
##     mode: '0644'
##     owner: "{{ ansible_user_id }}"
##     group: "{{ ansible_user_id }}"

- name: Create Sway desktop entry for LightDM, GDM, or SDDM
  copy:
    dest: /usr/share/wayland-sessions/sway.desktop
    content: |
      [Desktop Entry]
      Name=Sway
      Comment=An i3-compatible Wayland compositor
      Exec=sway
      Type=Application
      DesktopNames=Sway
    mode: '0644'

- name: Ensure LightDM configuration exists
  blockinfile:
    path: /etc/lightdm/lightdm.conf
    block: |
      [Seat:*]
      user-session=sway
      session-wrapper=/etc/lightdm/Xsession

- name: Set environment variables in .profile
  lineinfile:
    path: /home/{{ ansible_user_id }}/.profile
    line: "{{ item }}"
    create: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - 'export XDG_CURRENT_DESKTOP=sway'
    - 'export XDG_SESSION_TYPE=wayland'
    - 'export MOZ_ENABLE_WAYLAND=1'
    - 'export QT_QPA_PLATFORM=wayland'

# - name: Reboot the system
#   reboot:
#     msg: "Reboot initiated by Ansible for SwayWM installation"
#     connect_timeout: 5
#     reboot_timeout: 600
#     pre_reboot_delay: 0
#     post_reboot_delay: 30
#     test_command: whoami
