---
- name: Setup Development Environment for Work Machine
  hosts: work_machine
  connection: local
  become: yes

  vars_files:
    - vars/common.yml

  roles:
    - dotfiles
    - nvim

- name: Setup Development Environment for Work Machine
  hosts: swaywm
  connection: local
  become: yes

  vars_files:
    - vars/common.yml

  roles:
    - sway
