[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true
show_hidden = true
show_symlink = true
linemode = "size"

[preview]
max_width = 1000
max_height = 1000

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = "edit" },
  { mime = "application/json", use = "edit" },
  { mime = "*/xml", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.yaml", use = "edit" },
  { name = "*.yml", use = "edit" },
]
