---
- hosts: all
  become: true
  pre_tasks:

    - name: update repository index
      tags: always
      apt:
        cache_valid_time: 3600
        update_cache: yes
      changed_when: false

- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: server
  roles:
    - server
  tags:
    - server

- hosts: workstation
  roles:
    - workstation
  tags:
    - workstation
