ansible_become_password: ENC[AES256_GCM,data:c+wz/51KIjMNwA==,iv:sPqA/hVSa8JltKEsU/dN577tEspMy1uHTelPdhpkJy8=,tag:Ur9770vP9CPrluCy9BEuzA==,type:str]
sops:
    age:
        - recipient: age1duazmy5j6clvqkmnwtkjfnmk0n5kts0udac2qfeun5z2p6cw74kqa72z8f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NEtkTHVtWEJGY3JkSWpw
            QW1EaFZWQ0Jpd2t3U0Ryb3VSbVM5aTFVTjAwCjhWQlVzOUZvQ0RVLzl2Sm1DQVU5
            WmlTbWNjUXAwYmMyZCsxNHlXM3RKTzAKLS0tIHZONEZKNFVPTkJzRlNmSEJnMzJx
            eEJkZ2lzaEcyRVkzdUlZd2RSOTNQVjgK3EW/Uuzx9QL80C+krs6NoqTCfjisq8Y9
            PsI1kdyIlIp8rComlH7Ev7JhvvtE/1PdGPmdmN31D33pKnMR/+oT+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T21:01:44Z"
    mac: ENC[AES256_GCM,data:tsPHcXKbar0nGnkg+gi5wu/YwYtXE+MZbhxgVer9ddIYx3LsjCcZJWRRPV7vzg1eLDklXHnMvuLDQA/eL17QjPDbaHXHa0bMritKlvfvZt6RmxgpZXujzdaJFSA8y39a+wX4ziWqex3BsykJnkg4uzH7jRfYfZnnGP6wNV/9UL4=,iv:hqoTjnW9patHm579bil42F5EEHqmIhXoIpUtelqL+8I=,tag:Xd4JYSklDX9tFiOUw4EyHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
