ansible_become_password: ENC[AES256_GCM,data:c+wz/51KIjMNwA==,iv:sPqA/hVSa8JltKEsU/dN577tEspMy1uHTelPdhpkJy8=,tag:Ur9770vP9CPrluCy9BEuzA==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:K2OD7LNetDCfyC0HztYltDkn/TbA6WBl0hcTreO+pDzS+2Xy,iv:cZ0BM72X+cgS8H0fdpR9Fxp/h2lk1k+y93OecYFJ10s=,tag:8zFOvEC1grrCzztQxZnlVQ==,type:str]
cloudflare_dns_api_token: ENC[AES256_GCM,data:BoLJmlVTWcGRzcFwNa0GbFYNr1ETjo/zMM25aW29Bi39IkKvWLTs7/ZSRycGIzYgIOkUGio=,iv:bGRhJx8YHXtjyttDv0zyCDBYorFt4OoZC5UIPHlD/wc=,tag:oH9rmu04AHPgzzPoNwYvbQ==,type:str]
traefik_dashboard_auth: ENC[AES256_GCM,data:CxIfOF3dv3XWu+wI5/m3xNS/61xKglTVWw5FNMQxCuglcrEMggIrf/Rewgf93ve67W628SoBncxGCcWaRQUF9ztb,iv:jax2mgY2nYY8daNsbCQDr7Me6OyP6J1xD5R+Xc6P98s=,tag:cAzcJ8riads2gD88ovTjSg==,type:str]
sops:
    age:
        - recipient: age1duazmy5j6clvqkmnwtkjfnmk0n5kts0udac2qfeun5z2p6cw74kqa72z8f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NEtkTHVtWEJGY3JkSWpw
            QW1EaFZWQ0Jpd2t3U0Ryb3VSbVM5aTFVTjAwCjhWQlVzOUZvQ0RVLzl2Sm1DQVU5
            WmlTbWNjUXAwYmMyZCsxNHlXM3RKTzAKLS0tIHZONEZKNFVPTkJzRlNmSEJnMzJx
            eEJkZ2lzaEcyRVkzdUlZd2RSOTNQVjgK3EW/Uuzx9QL80C+krs6NoqTCfjisq8Y9
            PsI1kdyIlIp8rComlH7Ev7JhvvtE/1PdGPmdmN31D33pKnMR/+oT+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T11:06:56Z"
    mac: ENC[AES256_GCM,data:zNWVqYELESdIutO8m82VAGG0xfhqOKk3gWiyAM3r/dRWMBNWAvo8P8zAVoauro/j/raMqmxiwgXo48oUJWdEAn+C4IpzrG4z/ImAikNYvoYA7SXmxopBw1JrMvLA6xb3o9Ts0qrylk/YAYk5LeueG76TEW4GmbKS7pfdWJmq9iA=,iv:eRtmOnIFhj/WG6q1euJBVfszxcMxUqGnM8EYDcVzlXE=,tag:qFsnCDVLRMnEpNJ2U5em2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
